export {
  getAboutInfo,
  getDataCenterDevelopmentInfo,
  getDataCenterInfo,
  getDeliveryInfo,
  getLeasingInfo,
  getMassMedia,
  getMassMediaById,
  getMassMediaBySlug,
  getPaymentInfo,
} from './api';
export type {
  IAboutInfo,
  IAdvantage,
  IDataCenterDevelopmentAbout,
  IDataCenterDevelopmentInfo,
  IDataCenterDevelopmentStage,
  IDataCenterDevelopmentVariable,
  IDataCenterInfo,
  IDataCenterPhotos,
  IDeliveryAndPaymentInfo,
  ILeasingInfo,
  IMassMedia,
  ITariff,
} from './model';
