import '@/shared/styles/index.css';
import 'swiper/css';
import 'swiper/css/effect-fade';
import 'swiper/css/pagination';

import type { Metadata } from 'next';
import React from 'react';

import { Layout } from '@/shared/ui';
import { Footer, Header } from '@/widgets';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='ru'>
            <body>
                <Layout headerSlot={<Header />} footerSlot={<Footer />}>
                    {children}
                </Layout>
                <div id={'portal'} />
            </body>
        </html>
    );
}
